name:                 hello-world
version:              1.1.0.5
visibility:           public
id:                   hello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ
key:                  hello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ
abi:                  e8b3bb4e0080797f51fc54e9c6828ca3
exposed:              True
exposed-modules:      HelloWorld
hidden-modules:       Paths_hello_world
import-dirs:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/lib/aarch64-osx-ghc-9.6.7/hello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ

library-dirs:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/lib/aarch64-osx-ghc-9.6.7/hello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ

library-dirs-static:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/lib/aarch64-osx-ghc-9.6.7/hello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ

dynamic-library-dirs:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/lib/aarch64-osx-ghc-9.6.7

data-dir:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/share/aarch64-osx-ghc-9.6.7/hello-world-1.1.0.5

hs-libraries:         HShello-world-1.1.0.5-KnF0miZfFYuBQUVjkEzeQQ
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/doc/hello-world-1.1.0.5/hello-world.haddock

haddock-html:
    /Users/fresult/Documents/projects/practices/just-exercism/haskell/hello-world/.stack-work/install/aarch64-osx/854a68b0b7ecd1e348fb05354790b397fd7bc6635d52ae549830c21913bbe2bb/9.6.7/doc/hello-world-1.1.0.5
